"""
Guardrail service for validating and sanitizing LLM outputs.

This module uses the `guardrails` library to enforce safety checks such as
toxicity detection and PII redaction based on the configured security level.
"""
from guardrails import Guard
# from guardrails.hub import ToxicLanguage, DetectPII
# from guardrails.types import OnFailAction
from config import CONFIG

def setup_guard(guardrail_level: str = None):
    """
    Configures and returns a Guard object based on the specified level.

    Args:
        guardrail_level (str, optional): The level of guardrails to apply ('basic', 'strict', 'custom', 'none').
                                         Defaults to the value in CONFIG.

    Returns:
        Guard: A configured Guard object, or None if level is 'none'.

    Raises:
        ValueError: If an invalid guardrail level is provided.
    """
    if guardrail_level is None:
        guardrail_level = CONFIG["default_guardrail_option"]

    guard = None

    if guardrail_level.lower() == "none":
        guard = None

    elif guardrail_level == "basic":
        guard = Guard().use(
            ToxicLanguage(threshold=CONFIG["toxicity_threshold_basic"])
        )

    elif guardrail_level == "strict":
        guard = Guard().use(
            ToxicLanguage(threshold=CONFIG["toxicity_threshold_strict"])
        ).use(
            DetectPII(
                pii_entities=CONFIG["pii_entities_strict"],
                on_fail=getattr(OnFailAction, CONFIG["onfailaction_strict"].upper())
            )
        )

    elif guardrail_level == "custom":
        guard = Guard().use(
            ToxicLanguage(
                threshold=CONFIG["toxicity_threshold_custom"],
                validation_method="sentence"
            )
        ).use(
            DetectPII(
                pii_entities=CONFIG["pii_entities_custom"],
                on_fail=getattr(OnFailAction, CONFIG["onfailaction_custom"].upper())
            )
        )

    else:
        raise ValueError(f"Invalid guardrail level: {guardrail_level}")

    return guard


def validate_output(final_answer: str, guardrail_level: str = None):
    """
    Validates the LLM output against the configured guardrails.

    Args:
        final_answer (str): The text generated by the LLM.
        guardrail_level (str, optional): The level of guardrails to apply. Defaults to proper config.

    Returns:
        dict: A dictionary containing the 'answer' key with the validated (or blocked) text.
    """
    guard = setup_guard(guardrail_level)

    if guard:
        try:
            validated = guard.validate(final_answer)
            final_answer = validated.validated_output.strip()
        except Exception as e:
            return {"answer": f"⚠️ Response blocked by guardrail: {str(e)}"}

    return {"answer": final_answer}
