# version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: rag_backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=chatbot_db
      - DB_USER=user
      - DB_PASSWORD=password
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
      - DEFAULT_VECTOR_DB=Chroma
      - PHOENIX_COLLECTOR_ENDPOINT=http://20.98.116.35:5000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://20.98.116.35:5000/v1/traces
      - OTEL_PROJECT_NAME="RAGBOT_API"
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - chatbot_network
    depends_on:
      chromadb:
        condition: service_started
      phoenix:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - app-db:/app/db
      - rag_data:/app/data_directory # Shared volume for files

  ingestion-pool:
    build:
      context: ./ingestion_pool
      dockerfile: Dockerfile
    container_name: ingestion_pool
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=chatbot_db
      - DB_USER=user
      - DB_PASSWORD=password
      - INGESTION_POOL_SIZE=2
      - PHOENIX_COLLECTOR_ENDPOINT=http://20.98.116.35:5000
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
      # API Keys for embeddings which now happen here
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
    networks:
      - chatbot_network
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      chromadb:
        condition: service_started
    volumes:
      - app-db:/app/db
      - rag_data:/app/data_directory # Shared volume for files

  worker-pool:
    build: worker_pool
    command: python main.py
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=chatbot_db
      - DB_USER=user
      - DB_PASSWORD=password
      - WORKER_POOL_SIZE=2
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
      - DEFAULT_VECTOR_DB=Chroma
      # - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PHOENIX_COLLECTOR_ENDPOINT=http://20.98.116.35:5000
      - PYTHONPATH=/app
      # API Keys for Generation/Reranking
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
    networks:
      - chatbot_network
    depends_on:
      chromadb:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      backend:
        condition: service_started
    deploy:
      replicas: 1
    volumes:
      - app-db:/app/db
      - rag_data:/app/data_directory # Shared volume for files

  frontend:
    build:
      context: ./Frontend/docu-chatter-main
      dockerfile: Dockerfile
    container_name: rag_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend/docu-chatter-main:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://172.200.163.232:8000
    networks:
      - chatbot_network

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    # environment:
    #   - IS_PERSISTENT=TRUE
    #   - PERSIST_DIRECTORY=/data
    volumes:
      - chroma_data:/data
    networks:
      chatbot_network:
        aliases:
          - chromadb

  phoenix:
    image: arizephoenix/phoenix
    ports:
      - "6006:6006"
      - "4317:4317" # OTLP gRPC collector
      - "9090:9090"
    environment:
      - PHOENIX_PORT=6006
      - PHOENIX_GRPC_PORT=4317
      - PHOENIX_WORKING_DIR=/mnt/data

    volumes:
      - phoenix_data:/mnt/data
    networks:
      chatbot_network:
        aliases:
          - phoenix

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    networks:
      chatbot_network:
        aliases:
          - redis
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    networks:
      chatbot_network:
        aliases:
          - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d chatbot_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  chatbot_network:
    driver: bridge

volumes:
  chroma_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local
  phoenix_data:
    driver: local
  app-db:
  rag_data:
    # New shared volume

